/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/protech/models/macbook-rigged.glb --types --output _inspect/MacbookRigged.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_99: THREE.Mesh
    Object_101: THREE.Mesh
    Object_103: THREE.Mesh
    Object_105: THREE.Mesh
    Object_107: THREE.Mesh
    Object_109: THREE.Mesh
    Object_111: THREE.Mesh
    Object_113: THREE.Mesh
    Object_115: THREE.Mesh
    Object_117: THREE.Mesh
    Object_119: THREE.Mesh
    Object_121: THREE.Mesh
    Object_123: THREE.Mesh
    Object_125: THREE.Mesh
    Object_127: THREE.Mesh
    Object_129: THREE.Mesh
    Object_131: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_58: THREE.Mesh
    Object_60: THREE.Mesh
    Object_62: THREE.Mesh
    Object_64: THREE.Mesh
    Object_66: THREE.Mesh
    Object_68: THREE.Mesh
    Object_70: THREE.Mesh
    Object_72: THREE.Mesh
    Object_74: THREE.Mesh
    Object_76: THREE.Mesh
    Object_78: THREE.Mesh
    Object_80: THREE.Mesh
    Object_82: THREE.Mesh
    Object_84: THREE.Mesh
    Object_86: THREE.Mesh
    Object_88: THREE.Mesh
    Object_90: THREE.Mesh
    Object_92: THREE.Mesh
    Object_94: THREE.Mesh
    Object_96: THREE.Mesh
  }
  materials: {
    wjAYtisbflXilXi: THREE.MeshStandardMaterial
    zobIbiekuagXEVU: THREE.MeshStandardMaterial
    RyKTMHTpkkwQkvB: THREE.MeshStandardMaterial
    jwuTsnFxKtBUxpK: THREE.MeshStandardMaterial
    JvMFZolVCdpPqjj: THREE.MeshStandardMaterial
    UBYmHfGRfHbOXyc: THREE.MeshStandardMaterial
    uInNDOueKeBTGQB: THREE.MeshStandardMaterial
    gOXiFODBFKnUyyU: THREE.MeshStandardMaterial
    eBwkWuOBScacrgP: THREE.MeshStandardMaterial
    nDsMUuDKliqGFdU: THREE.MeshStandardMaterial
    sfCQkHOWyrsLmor: THREE.MeshStandardMaterial
    CdgEAaPUlrQWQuD: THREE.MeshStandardMaterial
    ZCDwChwkbBfITSW: THREE.MeshStandardMaterial
    XCYkeTCxqFmKTKe: THREE.MeshStandardMaterial
    MycfwscjQZRVSoj: THREE.MeshStandardMaterial
    AibnXCKcAbewWhH: THREE.MeshStandardMaterial
    WeLyzRwUVIhQGgM: THREE.MeshStandardMaterial
    UhoCLqHkvkDmxOA: THREE.MeshStandardMaterial
    zhGRTuGrQoJflBD: THREE.MeshStandardMaterial
    zCLdUynNQOzVMqx: THREE.MeshStandardMaterial
    lmWQsEjxpsebDlK: THREE.MeshStandardMaterial
    bsmYIMHYRqMuLqz: THREE.MeshStandardMaterial
    LtEafgAVRolQqRw: THREE.MeshStandardMaterial
    iyDJFXmHelnMTbD: THREE.MeshStandardMaterial
    eJObPwhgFzvfaoZ: THREE.MeshStandardMaterial
    CRQixVLpahJzhJc: THREE.MeshStandardMaterial
    IcpudUyxprDYhfw: THREE.MeshStandardMaterial
    YYwBgwvcyZVOOAA: THREE.MeshStandardMaterial
    SLGkCohDDelqXBu: THREE.MeshStandardMaterial
    WDumMKBWVQxmraD: THREE.MeshStandardMaterial
    WnHKXHhScfUbJQi: THREE.MeshStandardMaterial
    ZNhRrZtaKWQYAab: THREE.MeshStandardMaterial
    fNHiBfcxHUJCahl: THREE.MeshStandardMaterial
    bsEIHfblEXNcUMs: THREE.MeshStandardMaterial
    SABLxXNNESCdgUy: THREE.MeshStandardMaterial
    LpqXZqhaGCeSzdu: THREE.MeshStandardMaterial
    sIfSZcqgDlKMJPf: THREE.MeshStandardMaterial
    gMtYExgrEUqPfln: THREE.MeshStandardMaterial
    hmEmmncwVomyUTC: THREE.MeshStandardMaterial
    KclpPzxoRwZAoer: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/macbook-rigged.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.35, -11.82]}>
        <group position={[0, 0.35, 11.82]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_99.geometry} material={materials.wjAYtisbflXilXi} />
          <mesh geometry={nodes.Object_101.geometry} material={materials.zobIbiekuagXEVU} />
          <mesh geometry={nodes.Object_103.geometry} material={materials.RyKTMHTpkkwQkvB} />
          <mesh geometry={nodes.Object_105.geometry} material={materials.jwuTsnFxKtBUxpK} />
          <mesh geometry={nodes.Object_107.geometry} material={materials.JvMFZolVCdpPqjj} />
          <mesh geometry={nodes.Object_109.geometry} material={materials.UBYmHfGRfHbOXyc} />
          <mesh geometry={nodes.Object_111.geometry} material={materials.uInNDOueKeBTGQB} />
          <mesh geometry={nodes.Object_113.geometry} material={materials.gOXiFODBFKnUyyU} />
          <mesh geometry={nodes.Object_115.geometry} material={materials.eBwkWuOBScacrgP} />
          <mesh geometry={nodes.Object_117.geometry} material={materials.jwuTsnFxKtBUxpK} />
          <mesh geometry={nodes.Object_119.geometry} material={materials.jwuTsnFxKtBUxpK} />
          <mesh geometry={nodes.Object_121.geometry} material={materials.nDsMUuDKliqGFdU} />
          <mesh geometry={nodes.Object_123.geometry} material={materials.sfCQkHOWyrsLmor} />
          <mesh geometry={nodes.Object_125.geometry} material={materials.CdgEAaPUlrQWQuD} />
          <mesh geometry={nodes.Object_127.geometry} material={materials.ZCDwChwkbBfITSW} />
          <mesh geometry={nodes.Object_129.geometry} material={materials.XCYkeTCxqFmKTKe} />
          <mesh geometry={nodes.Object_131.geometry} material={materials.MycfwscjQZRVSoj} />
        </group>
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.AibnXCKcAbewWhH} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.WeLyzRwUVIhQGgM} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.UhoCLqHkvkDmxOA} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.zhGRTuGrQoJflBD} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.zCLdUynNQOzVMqx} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.jwuTsnFxKtBUxpK} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.lmWQsEjxpsebDlK} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.jwuTsnFxKtBUxpK} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.MycfwscjQZRVSoj} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.bsmYIMHYRqMuLqz} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.LtEafgAVRolQqRw} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.iyDJFXmHelnMTbD} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.eJObPwhgFzvfaoZ} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.jwuTsnFxKtBUxpK} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.nDsMUuDKliqGFdU} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.LtEafgAVRolQqRw} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.CRQixVLpahJzhJc} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.IcpudUyxprDYhfw} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.jwuTsnFxKtBUxpK} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.YYwBgwvcyZVOOAA} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.jwuTsnFxKtBUxpK} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.jwuTsnFxKtBUxpK} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.SLGkCohDDelqXBu} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.WDumMKBWVQxmraD} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.WnHKXHhScfUbJQi} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.jwuTsnFxKtBUxpK} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.ZNhRrZtaKWQYAab} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.IcpudUyxprDYhfw} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.fNHiBfcxHUJCahl} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.bsEIHfblEXNcUMs} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.CRQixVLpahJzhJc} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.SABLxXNNESCdgUy} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.LpqXZqhaGCeSzdu} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.sIfSZcqgDlKMJPf} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.bsmYIMHYRqMuLqz} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.jwuTsnFxKtBUxpK} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.gMtYExgrEUqPfln} />
        <mesh geometry={nodes.Object_84.geometry} material={materials.WnHKXHhScfUbJQi} />
        <mesh geometry={nodes.Object_86.geometry} material={materials.nDsMUuDKliqGFdU} />
        <mesh geometry={nodes.Object_88.geometry} material={materials.bsEIHfblEXNcUMs} />
        <mesh geometry={nodes.Object_90.geometry} material={materials.uInNDOueKeBTGQB} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.hmEmmncwVomyUTC} />
        <mesh geometry={nodes.Object_94.geometry} material={materials.WeLyzRwUVIhQGgM} />
        <mesh geometry={nodes.Object_96.geometry} material={materials.KclpPzxoRwZAoer} />
      </group>
    </group>
  )
}

useGLTF.preload('/macbook-rigged.glb')
